import { useState, useRef, useEffect, KeyboardEvent } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Send,
  Sparkles,
  User,
  Bot,
  Trash2,
  RotateCcw,
  Lightbulb,
} from "lucide-react";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

interface PromptPanelProps {
  onCodeGenerated: (code: string) => void;
}

const SAMPLE_PROMPTS = [
  "Create a modern portfolio with dark theme",
  "Build a restaurant landing page with menu section",
  "Design a SaaS pricing page with 3 tiers",
  "Make a personal blog with card-style posts",
];

// Mock AI response with generated HTML
const generateMockResponse = (prompt: string): string => {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Generated Website</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', system-ui, sans-serif;
      background: linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 100%);
      color: #f0f0ff;
      min-height: 100vh;
    }
    .hero {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 2rem;
    }
    .hero h1 {
      font-size: 3.5rem;
      font-weight: 800;
      background: linear-gradient(135deg, #6C63FF, #FF6584);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 1rem;
    }
    .hero p {
      font-size: 1.2rem;
      color: rgba(255,255,255,0.6);
      max-width: 600px;
      line-height: 1.8;
    }
    .cta {
      margin-top: 2rem;
      padding: 0.875rem 2.5rem;
      background: #6C63FF;
      color: white;
      border: none;
      border-radius: 12px;
      font-size: 1rem;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s;
    }
    .cta:hover { background: #5A52E0; transform: translateY(-2px); }
    .features {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 1.5rem;
      padding: 4rem 2rem;
      max-width: 1200px;
      margin: 0 auto;
    }
    .card {
      background: rgba(255,255,255,0.04);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 16px;
      padding: 2rem;
      backdrop-filter: blur(10px);
      transition: all 0.3s;
    }
    .card:hover {
      border-color: rgba(108,99,255,0.3);
      transform: translateY(-4px);
      box-shadow: 0 8px 30px rgba(108,99,255,0.15);
    }
    .card h3 { font-size: 1.25rem; margin-bottom: 0.75rem; }
    .card p { color: rgba(255,255,255,0.5); line-height: 1.6; font-size: 0.9rem; }
  </style>
</head>
<body>
  <section class="hero">
    <h1>Welcome to the Future</h1>
    <p>This website was generated by AI based on your prompt: "${prompt}". It features a modern design with glassmorphism effects and gradient accents.</p>
    <button class="cta">Get Started</button>
  </section>
  <section class="features">
    <div class="card">
      <h3>⚡ Lightning Fast</h3>
      <p>Built with performance in mind. Every element is optimized for speed and efficiency.</p>
    </div>
    <div class="card">
      <h3>🎨 Beautiful Design</h3>
      <p>Modern aesthetics with carefully chosen colors, typography, and spacing.</p>
    </div>
    <div class="card">
      <h3>📱 Fully Responsive</h3>
      <p>Looks perfect on every device — from mobile phones to ultra-wide monitors.</p>
    </div>
  </section>
</body>
</html>`;
};

const PromptPanel = ({ onCodeGenerated }: PromptPanelProps) => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = `${Math.min(
        textareaRef.current.scrollHeight,
        150
      )}px`;
    }
  }, [input]);

  const handleSend = async () => {
    if (!input.trim() || isGenerating) return;

    const userMessage: Message = {
      id: `msg-${Date.now()}`,
      role: "user",
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsGenerating(true);

    // Simulate AI generation
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const code = generateMockResponse(userMessage.content);

    const aiMessage: Message = {
      id: `msg-${Date.now()}`,
      role: "assistant",
      content:
        "I've generated your website! Check the preview on the right. The design includes a hero section with gradient text, feature cards with glassmorphism, and hover animations. Want me to modify anything?",
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, aiMessage]);
    onCodeGenerated(code);
    setIsGenerating(false);
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleClear = () => {
    setMessages([]);
    onCodeGenerated("");
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-3.5 border-b border-[var(--brand-border)]">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-brand-primary/20 flex items-center justify-center">
            <Sparkles size={14} className="text-brand-primary" />
          </div>
          <span className="text-sm font-semibold text-[var(--text-secondary)]">
            AI Prompt
          </span>
        </div>
        {messages.length > 0 && (
          <button
            onClick={handleClear}
            className="p-1.5 rounded-lg text-[var(--text-faint)] hover:text-[var(--text-muted)] hover:bg-[var(--brand-glass-hover)] transition-colors"
            title="Clear conversation"
          >
            <Trash2 size={14} />
          </button>
        )}
      </div>

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {/* Welcome State */}
        {messages.length === 0 && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col items-center justify-center h-full text-center py-8"
          >
            <div className="w-14 h-14 rounded-2xl bg-brand-primary/10 flex items-center justify-center mb-4">
              <Sparkles size={24} className="text-brand-primary" />
            </div>
            <h3 className="text-base font-semibold text-[var(--text-secondary)] mb-1">
              What would you like to build?
            </h3>
            <p className="text-xs text-[var(--text-faint)] max-w-[260px] mb-6">
              Describe your website and AI will generate it for you instantly.
            </p>

            {/* Quick prompts */}
            <div className="w-full space-y-2">
              <div className="flex items-center gap-1.5 text-xs text-[var(--text-faint)] mb-2">
                <Lightbulb size={12} />
                <span>Try these</span>
              </div>
              {SAMPLE_PROMPTS.map((prompt, i) => (
                <motion.button
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.2 + i * 0.1 }}
                  onClick={() => setInput(prompt)}
                  className="w-full text-left px-3.5 py-2.5 rounded-xl text-xs text-[var(--text-muted)] hover:text-[var(--text-secondary)] bg-[var(--brand-glass)] hover:bg-[var(--brand-glass-hover)] border border-[var(--brand-border)] hover:border-[var(--brand-border-hover)] transition-all"
                >
                  "{prompt}"
                </motion.button>
              ))}
            </div>
          </motion.div>
        )}

        {/* Chat Messages */}
        <AnimatePresence>
          {messages.map((msg) => (
            <motion.div
              key={msg.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}
            >
              {/* Avatar */}
              <div
                className={`
                  w-7 h-7 rounded-lg flex items-center justify-center shrink-0 mt-0.5
                  ${
                    msg.role === "user"
                      ? "bg-brand-primary/20"
                      : "bg-emerald-500/20"
                  }
                `}
              >
                {msg.role === "user" ? (
                  <User size={13} className="text-brand-primary" />
                ) : (
                  <Bot size={13} className="text-emerald-400" />
                )}
              </div>

              {/* Bubble */}
              <div
                className={`
                  max-w-[85%] px-3.5 py-2.5 rounded-xl text-sm leading-relaxed
                  ${
                    msg.role === "user"
                      ? "bg-brand-primary/15 text-[var(--text-primary)] rounded-tr-sm"
                      : "bg-[var(--brand-glass)] text-[var(--text-secondary)] border border-[var(--brand-border)] rounded-tl-sm"
                  }
                `}
              >
                {msg.content}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {/* Typing Indicator */}
        {isGenerating && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex gap-3"
          >
            <div className="w-7 h-7 rounded-lg bg-emerald-500/20 flex items-center justify-center shrink-0">
              <Bot size={13} className="text-emerald-400" />
            </div>
            <div className="px-4 py-3 rounded-xl bg-[var(--brand-glass)] border border-[var(--brand-border)] rounded-tl-sm flex items-center gap-1.5">
              <span className="typing-dot" />
              <span className="typing-dot" />
              <span className="typing-dot" />
            </div>
          </motion.div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="px-4 py-3 border-t border-[var(--brand-border)]">
        <div className="relative flex items-end gap-2">
          <div className="flex-1 relative">
            <textarea
              ref={textareaRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Describe your website..."
              rows={1}
              disabled={isGenerating}
              className="w-full px-4 py-3 pr-12 text-sm glass-input text-[var(--text-primary)] placeholder:text-[var(--text-faint)] resize-none disabled:opacity-50"
              id="prompt-input"
            />
            <button
              onClick={handleSend}
              disabled={!input.trim() || isGenerating}
              className={`
                absolute right-2 bottom-2 p-2 rounded-lg transition-all
                ${
                  input.trim() && !isGenerating
                    ? "bg-brand-primary text-white hover:bg-brand-primary-hover shadow-lg shadow-brand-primary/25"
                    : "text-[var(--text-faint)] cursor-not-allowed"
                }
              `}
              aria-label="Send prompt"
            >
              {isGenerating ? (
                <RotateCcw size={16} className="animate-spin" />
              ) : (
                <Send size={16} />
              )}
            </button>
          </div>
        </div>
        <p className="text-[10px] text-[var(--text-faint)] mt-2 text-center">
          Press Enter to send · Shift+Enter for new line
        </p>
      </div>
    </div>
  );
};

export default PromptPanel;
