export async function mockGenerateHTML(
  prompt: string,
  onChunk: (chunk: string) => void,
  onDone: (fullHtml: string) => void
): Promise<void> {
  console.log('mockGenerateHTML called with:', prompt); // debug

  const MOCK_HTML = `
<section data-section-id="hero" class="bg-indigo-600 text-white py-20 px-8 text-center">
  <h1 class="text-5xl font-bold mb-4">${prompt}</h1>
  <p class="text-xl text-indigo-200">Generated by AI ✨</p>
</section>

<section data-section-id="footer" class="bg-gray-900 text-gray-400 py-8 text-center text-sm">
  <p>Built with ❤️ — AI Generated</p>
</section>
`.trim();

  console.log('Starting chunks...'); // debug

  const chunkSize = 50;
  const chunks = [];
  for (let i = 0; i < MOCK_HTML.length; i += chunkSize) {
    chunks.push(MOCK_HTML.slice(i, i + chunkSize));
  }

  let accumulated = '';
  for (const chunk of chunks) {
    await new Promise((res) => setTimeout(res, 30));
    accumulated += chunk;
    onChunk(accumulated);
  }

  console.log('Done! Final HTML length:', accumulated.length); // debug
  onDone(accumulated);
}