/**
 * tailwindCompiler.ts
 * 
 * Server-side Tailwind CSS v3 JIT generation.
 * Scans generated HTML for Tailwind class names → generates pure CSS → injects inline.
 * No CDN. No network calls. Fully self-contained output.
 */

/* eslint-disable @typescript-eslint/no-var-requires */
const postcss = require('postcss');
const tailwindcss = require('tailwindcss');

const HAS_TAILWIND_CDN = /cdn\.tailwindcss\.com/i;

// Common Tailwind class prefixes to detect usage
const TAILWIND_PATTERN = /class=["'][^"']*\b(bg-|text-|flex|grid|p-\d|m-\d|w-|h-|rounded|shadow|font-|border-|gap-|justify-|items-|container|mx-auto|py-|px-|mt-|mb-|ml-|mr-|space-|from-|to-|via-|gradient|opacity-|z-|overflow-|cursor-|transition|duration-|ease-|hover:|focus:|sm:|md:|lg:|xl:)\S*/i;

/** Detect if HTML uses Tailwind classes or CDN */
export function hasTailwindClasses(html: string): boolean {
  return HAS_TAILWIND_CDN.test(html) || TAILWIND_PATTERN.test(html);
}

/**
 * Generates Tailwind CSS for all classes used in the HTML.
 * Replaces CDN script/link tags with an inline <style> block.
 */
export async function injectTailwindCSS(html: string): Promise<string> {
  try {
    const result = await postcss([
      tailwindcss({
        content: [{ raw: html, extension: 'html' }],
        theme: { extend: {} },
        plugins: [],
        corePlugins: { preflight: true },
      }),
    ]).process('@tailwind base; @tailwind components; @tailwind utilities;', {
      from: undefined,
    });

    const generatedCSS = result.css;

    // Remove CDN tags
    let processed = html
      .replace(/<script[^>]*cdn\.tailwindcss\.com[^>]*>(<\/script>)?/gi, '')
      .replace(/<link[^>]*cdn\.tailwindcss\.com[^>]*\/?>/gi, '')
      .replace(/<link[^>]+href=["']https?:\/\/fonts\.googleapis[^"']*["'][^>]*\/?>/gi, '')
      .replace(/@import\s+url\(['"]?https?:\/\/fonts\.googleapis[^)]+['"]?\)\s*;?/gi, '');

    // Inject generated CSS
    const styleTag = `<style>\n/* Generated by Tailwind CSS v3 — no CDN */\n${generatedCSS}\n</style>`;

    if (/<\/head>/i.test(processed)) {
      processed = processed.replace(/<\/head>/i, `${styleTag}\n</head>`);
    } else {
      processed = styleTag + '\n' + processed;
    }

    return processed;
  } catch (err) {
    console.error('[tailwindCompiler] CSS generation failed:', err);
    // Fallback: just strip CDN, return unstyled
    return html
      .replace(/<script[^>]*cdn\.tailwindcss\.com[^>]*>(<\/script>)?/gi, '')
      .replace(/<link[^>]*cdn\.tailwindcss\.com[^>]*\/?>/gi, '');
  }
}
